apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: vishnusunil243/cartservice:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        env:
        - name: DB_KEY
          value: "host=cart-service user=postgres password=8129 dbname=carts port=5432 sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
  - port: 8083
    targetPort: 8083


